/*
 * This file is generated by jOOQ.
 */
package com.jooq;


import com.jooq.tables.ApiConfig;
import com.jooq.tables.CaseDetail;
import com.jooq.tables.CaseGroup;
import com.jooq.tables.TestConfig;
import com.jooq.tables.UserDefineParam;
import com.jooq.tables.UserInfo;
import com.jooq.tables.records.ApiConfigRecord;
import com.jooq.tables.records.CaseDetailRecord;
import com.jooq.tables.records.CaseGroupRecord;
import com.jooq.tables.records.TestConfigRecord;
import com.jooq.tables.records.UserDefineParamRecord;
import com.jooq.tables.records.UserInfoRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * apitest.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ApiConfigRecord> KEY_API_CONFIG_PRIMARY = Internal.createUniqueKey(ApiConfig.API_CONFIG, DSL.name("KEY_api_config_PRIMARY"), new TableField[] { ApiConfig.API_CONFIG.ID }, true);
    public static final UniqueKey<CaseDetailRecord> KEY_CASE_DETAIL_PRIMARY = Internal.createUniqueKey(CaseDetail.CASE_DETAIL, DSL.name("KEY_case_detail_PRIMARY"), new TableField[] { CaseDetail.CASE_DETAIL.ID }, true);
    public static final UniqueKey<CaseGroupRecord> KEY_CASE_GROUP_PRIMARY = Internal.createUniqueKey(CaseGroup.CASE_GROUP, DSL.name("KEY_case_group_PRIMARY"), new TableField[] { CaseGroup.CASE_GROUP.ID }, true);
    public static final UniqueKey<TestConfigRecord> KEY_TEST_CONFIG_PRIMARY = Internal.createUniqueKey(TestConfig.TEST_CONFIG, DSL.name("KEY_test_config_PRIMARY"), new TableField[] { TestConfig.TEST_CONFIG.ID }, true);
    public static final UniqueKey<UserDefineParamRecord> KEY_USER_DEFINE_PARAM_PRIMARY = Internal.createUniqueKey(UserDefineParam.USER_DEFINE_PARAM, DSL.name("KEY_user_define_param_PRIMARY"), new TableField[] { UserDefineParam.USER_DEFINE_PARAM.ID }, true);
    public static final UniqueKey<UserInfoRecord> KEY_USER_INFO_PRIMARY = Internal.createUniqueKey(UserInfo.USER_INFO, DSL.name("KEY_user_info_PRIMARY"), new TableField[] { UserInfo.USER_INFO.ID }, true);
}
