/*
 * This file is generated by jOOQ.
 */
package com.jooq;


import com.jooq.tables.ApiConfig;
import com.jooq.tables.CaseDetail;
import com.jooq.tables.CaseGroup;
import com.jooq.tables.TestConfig;
import com.jooq.tables.UserDefineParam;
import com.jooq.tables.UserInfo;


/**
 * Convenience access to all tables in apitest.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>apitest.api_config</code>.
     */
    public static final ApiConfig API_CONFIG = ApiConfig.API_CONFIG;

    /**
     * The table <code>apitest.case_detail</code>.
     */
    public static final CaseDetail CASE_DETAIL = CaseDetail.CASE_DETAIL;

    /**
     * The table <code>apitest.case_group</code>.
     */
    public static final CaseGroup CASE_GROUP = CaseGroup.CASE_GROUP;

    /**
     * The table <code>apitest.test_config</code>.
     */
    public static final TestConfig TEST_CONFIG = TestConfig.TEST_CONFIG;

    /**
     * The table <code>apitest.user_define_param</code>.
     */
    public static final UserDefineParam USER_DEFINE_PARAM = UserDefineParam.USER_DEFINE_PARAM;

    /**
     * The table <code>apitest.user_info</code>.
     */
    public static final UserInfo USER_INFO = UserInfo.USER_INFO;
}
