/*
 * This file is generated by jOOQ.
 */
package com.jooq.tables.records;


import com.jooq.tables.ApiConfig;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApiConfigRecord extends UpdatableRecordImpl<ApiConfigRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>apitest.api_config.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apitest.api_config.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apitest.api_config.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>apitest.api_config.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>apitest.api_config.headers</code>.
     */
    public void setHeaders(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>apitest.api_config.headers</code>.
     */
    public String getHeaders() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ApiConfig.API_CONFIG.ID;
    }

    @Override
    public Field<String> field2() {
        return ApiConfig.API_CONFIG.URL;
    }

    @Override
    public Field<String> field3() {
        return ApiConfig.API_CONFIG.HEADERS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public String component3() {
        return getHeaders();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public String value3() {
        return getHeaders();
    }

    @Override
    public ApiConfigRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ApiConfigRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public ApiConfigRecord value3(String value) {
        setHeaders(value);
        return this;
    }

    @Override
    public ApiConfigRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApiConfigRecord
     */
    public ApiConfigRecord() {
        super(ApiConfig.API_CONFIG);
    }

    /**
     * Create a detached, initialised ApiConfigRecord
     */
    public ApiConfigRecord(Integer id, String url, String headers) {
        super(ApiConfig.API_CONFIG);

        setId(id);
        setUrl(url);
        setHeaders(headers);
    }
}
