/*
 * This file is generated by jOOQ.
 */
package com.jooq.tables.records;


import com.jooq.tables.CaseGroup;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseGroupRecord extends UpdatableRecordImpl<CaseGroupRecord> implements Record4<String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>apitest.case_group.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>apitest.case_group.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>apitest.case_group.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>apitest.case_group.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>apitest.case_group.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>apitest.case_group.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>apitest.case_group.update_time</code>. 修改时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>apitest.case_group.update_time</code>. 修改时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CaseGroup.CASE_GROUP.ID;
    }

    @Override
    public Field<String> field2() {
        return CaseGroup.CASE_GROUP.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return CaseGroup.CASE_GROUP.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return CaseGroup.CASE_GROUP.UPDATE_TIME;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component4() {
        return getUpdateTime();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value4() {
        return getUpdateTime();
    }

    @Override
    public CaseGroupRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public CaseGroupRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public CaseGroupRecord value3(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public CaseGroupRecord value4(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public CaseGroupRecord values(String value1, String value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CaseGroupRecord
     */
    public CaseGroupRecord() {
        super(CaseGroup.CASE_GROUP);
    }

    /**
     * Create a detached, initialised CaseGroupRecord
     */
    public CaseGroupRecord(String id, String description, LocalDateTime createTime, LocalDateTime updateTime) {
        super(CaseGroup.CASE_GROUP);

        setId(id);
        setDescription(description);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }
}
