/*
 * This file is generated by jOOQ.
 */
package com.jooq.tables.records;


import com.jooq.tables.CaseDetail;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaseDetailRecord extends UpdatableRecordImpl<CaseDetailRecord> implements Record12<Integer, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>apitest.case_detail.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apitest.case_detail.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apitest.case_detail.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>apitest.case_detail.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>apitest.case_detail.path</code>.
     */
    public void setPath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>apitest.case_detail.path</code>.
     */
    public String getPath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>apitest.case_detail.header</code>.
     */
    public void setHeader(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>apitest.case_detail.header</code>.
     */
    public String getHeader() {
        return (String) get(3);
    }

    /**
     * Setter for <code>apitest.case_detail.method</code>.
     */
    public void setMethod(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>apitest.case_detail.method</code>.
     */
    public String getMethod() {
        return (String) get(4);
    }

    /**
     * Setter for <code>apitest.case_detail.data</code>.
     */
    public void setData(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>apitest.case_detail.data</code>.
     */
    public String getData() {
        return (String) get(5);
    }

    /**
     * Setter for <code>apitest.case_detail.assertions</code>.
     */
    public void setAssertions(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>apitest.case_detail.assertions</code>.
     */
    public String getAssertions() {
        return (String) get(6);
    }

    /**
     * Setter for <code>apitest.case_detail.extract</code>.
     */
    public void setExtract(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>apitest.case_detail.extract</code>.
     */
    public String getExtract() {
        return (String) get(7);
    }

    /**
     * Setter for <code>apitest.case_detail.description</code>.
     */
    public void setDescription(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>apitest.case_detail.description</code>.
     */
    public String getDescription() {
        return (String) get(8);
    }

    /**
     * Setter for <code>apitest.case_detail.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>apitest.case_detail.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>apitest.case_detail.update_time</code>. 修改时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>apitest.case_detail.update_time</code>. 修改时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>apitest.case_detail.group_id</code>.
     */
    public void setGroupId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>apitest.case_detail.group_id</code>.
     */
    public String getGroupId() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CaseDetail.CASE_DETAIL.ID;
    }

    @Override
    public Field<String> field2() {
        return CaseDetail.CASE_DETAIL.URL;
    }

    @Override
    public Field<String> field3() {
        return CaseDetail.CASE_DETAIL.PATH;
    }

    @Override
    public Field<String> field4() {
        return CaseDetail.CASE_DETAIL.HEADER;
    }

    @Override
    public Field<String> field5() {
        return CaseDetail.CASE_DETAIL.METHOD;
    }

    @Override
    public Field<String> field6() {
        return CaseDetail.CASE_DETAIL.DATA;
    }

    @Override
    public Field<String> field7() {
        return CaseDetail.CASE_DETAIL.ASSERTIONS;
    }

    @Override
    public Field<String> field8() {
        return CaseDetail.CASE_DETAIL.EXTRACT;
    }

    @Override
    public Field<String> field9() {
        return CaseDetail.CASE_DETAIL.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return CaseDetail.CASE_DETAIL.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return CaseDetail.CASE_DETAIL.UPDATE_TIME;
    }

    @Override
    public Field<String> field12() {
        return CaseDetail.CASE_DETAIL.GROUP_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public String component3() {
        return getPath();
    }

    @Override
    public String component4() {
        return getHeader();
    }

    @Override
    public String component5() {
        return getMethod();
    }

    @Override
    public String component6() {
        return getData();
    }

    @Override
    public String component7() {
        return getAssertions();
    }

    @Override
    public String component8() {
        return getExtract();
    }

    @Override
    public String component9() {
        return getDescription();
    }

    @Override
    public LocalDateTime component10() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component11() {
        return getUpdateTime();
    }

    @Override
    public String component12() {
        return getGroupId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public String value3() {
        return getPath();
    }

    @Override
    public String value4() {
        return getHeader();
    }

    @Override
    public String value5() {
        return getMethod();
    }

    @Override
    public String value6() {
        return getData();
    }

    @Override
    public String value7() {
        return getAssertions();
    }

    @Override
    public String value8() {
        return getExtract();
    }

    @Override
    public String value9() {
        return getDescription();
    }

    @Override
    public LocalDateTime value10() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value11() {
        return getUpdateTime();
    }

    @Override
    public String value12() {
        return getGroupId();
    }

    @Override
    public CaseDetailRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CaseDetailRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public CaseDetailRecord value3(String value) {
        setPath(value);
        return this;
    }

    @Override
    public CaseDetailRecord value4(String value) {
        setHeader(value);
        return this;
    }

    @Override
    public CaseDetailRecord value5(String value) {
        setMethod(value);
        return this;
    }

    @Override
    public CaseDetailRecord value6(String value) {
        setData(value);
        return this;
    }

    @Override
    public CaseDetailRecord value7(String value) {
        setAssertions(value);
        return this;
    }

    @Override
    public CaseDetailRecord value8(String value) {
        setExtract(value);
        return this;
    }

    @Override
    public CaseDetailRecord value9(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public CaseDetailRecord value10(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public CaseDetailRecord value11(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public CaseDetailRecord value12(String value) {
        setGroupId(value);
        return this;
    }

    @Override
    public CaseDetailRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, LocalDateTime value10, LocalDateTime value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CaseDetailRecord
     */
    public CaseDetailRecord() {
        super(CaseDetail.CASE_DETAIL);
    }

    /**
     * Create a detached, initialised CaseDetailRecord
     */
    public CaseDetailRecord(Integer id, String url, String path, String header, String method, String data, String assertions, String extract, String description, LocalDateTime createTime, LocalDateTime updateTime, String groupId) {
        super(CaseDetail.CASE_DETAIL);

        setId(id);
        setUrl(url);
        setPath(path);
        setHeader(header);
        setMethod(method);
        setData(data);
        setAssertions(assertions);
        setExtract(extract);
        setDescription(description);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setGroupId(groupId);
    }
}
