/*
 * This file is generated by jOOQ.
 */
package com.jooq.tables.records;


import com.jooq.tables.UserDefineParam;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDefineParamRecord extends UpdatableRecordImpl<UserDefineParamRecord> implements Record7<Integer, Integer, String, LocalDateTime, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>apitest.user_define_param.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apitest.user_define_param.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apitest.user_define_param.case_group_id</code>.
     */
    public void setCaseGroupId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>apitest.user_define_param.case_group_id</code>.
     */
    public Integer getCaseGroupId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>apitest.user_define_param.user_define_parameters</code>.
     */
    public void setUserDefineParameters(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>apitest.user_define_param.user_define_parameters</code>.
     */
    public String getUserDefineParameters() {
        return (String) get(2);
    }

    /**
     * Setter for <code>apitest.user_define_param.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>apitest.user_define_param.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>apitest.user_define_param.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>apitest.user_define_param.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>apitest.user_define_param.create_at</code>.
     */
    public void setCreateAt(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>apitest.user_define_param.create_at</code>.
     */
    public String getCreateAt() {
        return (String) get(5);
    }

    /**
     * Setter for <code>apitest.user_define_param.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>apitest.user_define_param.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, String, LocalDateTime, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, String, LocalDateTime, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserDefineParam.USER_DEFINE_PARAM.ID;
    }

    @Override
    public Field<Integer> field2() {
        return UserDefineParam.USER_DEFINE_PARAM.CASE_GROUP_ID;
    }

    @Override
    public Field<String> field3() {
        return UserDefineParam.USER_DEFINE_PARAM.USER_DEFINE_PARAMETERS;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return UserDefineParam.USER_DEFINE_PARAM.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return UserDefineParam.USER_DEFINE_PARAM.UPDATE_TIME;
    }

    @Override
    public Field<String> field6() {
        return UserDefineParam.USER_DEFINE_PARAM.CREATE_AT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return UserDefineParam.USER_DEFINE_PARAM.UPDATE_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCaseGroupId();
    }

    @Override
    public String component3() {
        return getUserDefineParameters();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdateTime();
    }

    @Override
    public String component6() {
        return getCreateAt();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdateAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCaseGroupId();
    }

    @Override
    public String value3() {
        return getUserDefineParameters();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdateTime();
    }

    @Override
    public String value6() {
        return getCreateAt();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdateAt();
    }

    @Override
    public UserDefineParamRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value2(Integer value) {
        setCaseGroupId(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value3(String value) {
        setUserDefineParameters(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value5(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value6(String value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public UserDefineParamRecord value7(LocalDateTime value) {
        setUpdateAt(value);
        return this;
    }

    @Override
    public UserDefineParamRecord values(Integer value1, Integer value2, String value3, LocalDateTime value4, LocalDateTime value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDefineParamRecord
     */
    public UserDefineParamRecord() {
        super(UserDefineParam.USER_DEFINE_PARAM);
    }

    /**
     * Create a detached, initialised UserDefineParamRecord
     */
    public UserDefineParamRecord(Integer id, Integer caseGroupId, String userDefineParameters, LocalDateTime createTime, LocalDateTime updateTime, String createAt, LocalDateTime updateAt) {
        super(UserDefineParam.USER_DEFINE_PARAM);

        setId(id);
        setCaseGroupId(caseGroupId);
        setUserDefineParameters(userDefineParameters);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setCreateAt(createAt);
        setUpdateAt(updateAt);
    }
}
