/*
 * This file is generated by jOOQ.
 */
package com.jooq.tables.records;


import com.jooq.tables.UserInfo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoRecord extends UpdatableRecordImpl<UserInfoRecord> implements Record7<String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>apitest.user_info.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>apitest.user_info.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>apitest.user_info.user_account_id</code>.
     */
    public void setUserAccountId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>apitest.user_info.user_account_id</code>.
     */
    public String getUserAccountId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>apitest.user_info.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>apitest.user_info.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>apitest.user_info.openid</code>.
     */
    public void setOpenid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>apitest.user_info.openid</code>.
     */
    public String getOpenid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>apitest.user_info.tag</code>.
     */
    public void setTag(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>apitest.user_info.tag</code>.
     */
    public String getTag() {
        return (String) get(4);
    }

    /**
     * Setter for <code>apitest.user_info.telphone</code>.
     */
    public void setTelphone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>apitest.user_info.telphone</code>.
     */
    public String getTelphone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>apitest.user_info.type</code>.
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>apitest.user_info.type</code>.
     */
    public String getType() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return UserInfo.USER_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return UserInfo.USER_INFO.USER_ACCOUNT_ID;
    }

    @Override
    public Field<String> field3() {
        return UserInfo.USER_INFO.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return UserInfo.USER_INFO.OPENID;
    }

    @Override
    public Field<String> field5() {
        return UserInfo.USER_INFO.TAG;
    }

    @Override
    public Field<String> field6() {
        return UserInfo.USER_INFO.TELPHONE;
    }

    @Override
    public Field<String> field7() {
        return UserInfo.USER_INFO.TYPE;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserAccountId();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getOpenid();
    }

    @Override
    public String component5() {
        return getTag();
    }

    @Override
    public String component6() {
        return getTelphone();
    }

    @Override
    public String component7() {
        return getType();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserAccountId();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getOpenid();
    }

    @Override
    public String value5() {
        return getTag();
    }

    @Override
    public String value6() {
        return getTelphone();
    }

    @Override
    public String value7() {
        return getType();
    }

    @Override
    public UserInfoRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public UserInfoRecord value2(String value) {
        setUserAccountId(value);
        return this;
    }

    @Override
    public UserInfoRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserInfoRecord value4(String value) {
        setOpenid(value);
        return this;
    }

    @Override
    public UserInfoRecord value5(String value) {
        setTag(value);
        return this;
    }

    @Override
    public UserInfoRecord value6(String value) {
        setTelphone(value);
        return this;
    }

    @Override
    public UserInfoRecord value7(String value) {
        setType(value);
        return this;
    }

    @Override
    public UserInfoRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserInfoRecord
     */
    public UserInfoRecord() {
        super(UserInfo.USER_INFO);
    }

    /**
     * Create a detached, initialised UserInfoRecord
     */
    public UserInfoRecord(String id, String userAccountId, String password, String openid, String tag, String telphone, String type) {
        super(UserInfo.USER_INFO);

        setId(id);
        setUserAccountId(userAccountId);
        setPassword(password);
        setOpenid(openid);
        setTag(tag);
        setTelphone(telphone);
        setType(type);
    }
}
