/*
 * This file is generated by jOOQ.
 */
package com.jooq.tables;


import com.jooq.Apitest;
import com.jooq.Keys;
import com.jooq.tables.records.UserDefineParamRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDefineParam extends TableImpl<UserDefineParamRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>apitest.user_define_param</code>
     */
    public static final UserDefineParam USER_DEFINE_PARAM = new UserDefineParam();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserDefineParamRecord> getRecordType() {
        return UserDefineParamRecord.class;
    }

    /**
     * The column <code>apitest.user_define_param.id</code>.
     */
    public final TableField<UserDefineParamRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>apitest.user_define_param.case_group_id</code>.
     */
    public final TableField<UserDefineParamRecord, Integer> CASE_GROUP_ID = createField(DSL.name("case_group_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>apitest.user_define_param.user_define_parameters</code>.
     */
    public final TableField<UserDefineParamRecord, String> USER_DEFINE_PARAMETERS = createField(DSL.name("user_define_parameters"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>apitest.user_define_param.create_time</code>.
     */
    public final TableField<UserDefineParamRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>apitest.user_define_param.update_time</code>.
     */
    public final TableField<UserDefineParamRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>apitest.user_define_param.create_at</code>.
     */
    public final TableField<UserDefineParamRecord, String> CREATE_AT = createField(DSL.name("create_at"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>apitest.user_define_param.update_at</code>.
     */
    public final TableField<UserDefineParamRecord, LocalDateTime> UPDATE_AT = createField(DSL.name("update_at"), SQLDataType.LOCALDATETIME(0), this, "");

    private UserDefineParam(Name alias, Table<UserDefineParamRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserDefineParam(Name alias, Table<UserDefineParamRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>apitest.user_define_param</code> table reference
     */
    public UserDefineParam(String alias) {
        this(DSL.name(alias), USER_DEFINE_PARAM);
    }

    /**
     * Create an aliased <code>apitest.user_define_param</code> table reference
     */
    public UserDefineParam(Name alias) {
        this(alias, USER_DEFINE_PARAM);
    }

    /**
     * Create a <code>apitest.user_define_param</code> table reference
     */
    public UserDefineParam() {
        this(DSL.name("user_define_param"), null);
    }

    public <O extends Record> UserDefineParam(Table<O> child, ForeignKey<O, UserDefineParamRecord> key) {
        super(child, key, USER_DEFINE_PARAM);
    }

    @Override
    public Schema getSchema() {
        return Apitest.APITEST;
    }

    @Override
    public Identity<UserDefineParamRecord, Integer> getIdentity() {
        return (Identity<UserDefineParamRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserDefineParamRecord> getPrimaryKey() {
        return Keys.KEY_USER_DEFINE_PARAM_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserDefineParamRecord>> getKeys() {
        return Arrays.<UniqueKey<UserDefineParamRecord>>asList(Keys.KEY_USER_DEFINE_PARAM_PRIMARY);
    }

    @Override
    public UserDefineParam as(String alias) {
        return new UserDefineParam(DSL.name(alias), this);
    }

    @Override
    public UserDefineParam as(Name alias) {
        return new UserDefineParam(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDefineParam rename(String name) {
        return new UserDefineParam(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDefineParam rename(Name name) {
        return new UserDefineParam(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, String, LocalDateTime, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
